//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppConcentracionDeCargaHoraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtividadesDetalles
    {
        public int idAD { get; set; }
        public int idUsuario { get; set; }
        public int idDia { get; set; }
        public System.TimeSpan tmHoraEntrada { get; set; }
        public System.TimeSpan tmHoraSalida { get; set; }
        public double fltHorasPorDia { get; set; }
    
        public virtual tblUsuarios tblUsuarios { get; set; }
        public virtual tblDias tblDias { get; set; }
    }
}
