//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppConcentracionDeCargaHoraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDias
    {
        public tblDias()
        {
            this.tblAtividadesDetalles = new HashSet<tblAtividadesDetalles>();
            this.tblProgramarActividad = new HashSet<tblProgramarActividad>();
        }
    
        public int idDia { get; set; }
        public string vchDia { get; set; }
    
        public virtual ICollection<tblAtividadesDetalles> tblAtividadesDetalles { get; set; }
        public virtual ICollection<tblProgramarActividad> tblProgramarActividad { get; set; }
    }
}
