//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppConcentracionDeCargaHoraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProgramarActividad
    {
        public int idPA { get; set; }
        public int idUsuario { get; set; }
        public int idActividad { get; set; }
        public int idDia { get; set; }
        public System.TimeSpan tmHoraEmpieza { get; set; }
        public System.TimeSpan tmHoraFinaliza { get; set; }
        public string vchSalon { get; set; }
        public double fltHorasTrabajadas { get; set; }
    
        public virtual tblActividades tblActividades { get; set; }
        public virtual tblDias tblDias { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
