//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppConcentracionDeCargaHoraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuariosDetalle
    {
        public int idUD { get; set; }
        public int idUsuario { get; set; }
        public string vchCarrera { get; set; }
        public string vchPeriodo { get; set; }
        public double fltCargaHoraria { get; set; }
    
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
