//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppConcentracionDeCargaHoraria
{
    using System;
    using System.Collections.Generic;
    using MvcAppConcentracionDeCargaHoraria.Models;

    [System.ComponentModel.DataAnnotations.MetadataType(typeof(clsLoginValidar))]
    public partial class tblUsuarios
    {
        public tblUsuarios()
        {
            this.tblAtividadesDetalles = new HashSet<tblAtividadesDetalles>();
            this.tblProgramarActividad = new HashSet<tblProgramarActividad>();
            this.tblUsuariosDetalle = new HashSet<tblUsuariosDetalle>();
        }
    
        public int idUsuario { get; set; }
        public string vchEmail { get; set; }
        public string vchPass { get; set; }
    
        public virtual ICollection<tblAtividadesDetalles> tblAtividadesDetalles { get; set; }
        public virtual ICollection<tblProgramarActividad> tblProgramarActividad { get; set; }
        public virtual ICollection<tblUsuariosDetalle> tblUsuariosDetalle { get; set; }
    }
}
